export enum ClientMessageType {
  START_TRANSACTION = "START_TRANSACTION",
  METER_VALUE = "METER_VALUE",
  END_TRANSACTION = "END_TRANSACTION"
}

export enum ServerMessageType {
  CONNECTED = "CONNECTED",
  TRANSACTION_STARTED = "TRANSACTION_STARTED",
  METER_VALUE_ACCEPTED = "METER_VALUE_ACCEPTED",
  TRANSACTION_ENDED = "TRANSACTION_ENDED",
  ERROR = "ERROR"
}
